// Code generated by mockery v2.40.1. DO NOT EDIT.

package model

import mock "github.com/stretchr/testify/mock"

// MockSlide is an autogenerated mock type for the Slide type
type MockSlide struct {
	mock.Mock
}

// End provides a mock function with given fields:
func (_m *MockSlide) End() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for End")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Start provides a mock function with given fields:
func (_m *MockSlide) Start() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// NewMockSlide creates a new instance of MockSlide. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSlide(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSlide {
	mock := &MockSlide{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
