// Code generated by mockery v2.40.1. DO NOT EDIT.

package circularqueue

import mock "github.com/stretchr/testify/mock"

// MockCircularQueue is an autogenerated mock type for the CircularQueue type
type MockCircularQueue[T comparable] struct {
	mock.Mock
}

// Next provides a mock function with given fields:
func (_m *MockCircularQueue[T]) Next() (T, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 T
	var r1 error
	if rf, ok := ret.Get(0).(func() (T, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() T); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(T)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetFirst provides a mock function with given fields: entry
func (_m *MockCircularQueue[T]) SetFirst(entry T) error {
	ret := _m.Called(entry)

	if len(ret) == 0 {
		panic("no return value specified for SetFirst")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(T) error); ok {
		r0 = rf(entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockCircularQueue creates a new instance of MockCircularQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCircularQueue[T comparable](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCircularQueue[T] {
	mock := &MockCircularQueue[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
