// Code generated by mockery v2.40.1. DO NOT EDIT.

package timestamp

import mock "github.com/stretchr/testify/mock"

// MockFactory is an autogenerated mock type for the Factory type
type MockFactory struct {
	mock.Mock
}

// CurrentTime provides a mock function with given fields:
func (_m *MockFactory) CurrentTime() Timestamp {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CurrentTime")
	}

	var r0 Timestamp
	if rf, ok := ret.Get(0).(func() Timestamp); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(Timestamp)
	}

	return r0
}

// NewMockFactory creates a new instance of MockFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFactory {
	mock := &MockFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
