// Code generated by mockery v2.40.1. DO NOT EDIT.

package equality

import mock "github.com/stretchr/testify/mock"

// MockEqualsByValue is an autogenerated mock type for the EqualsByValue type
type MockEqualsByValue[T interface{}] struct {
	mock.Mock
}

// Equals provides a mock function with given fields: other
func (_m *MockEqualsByValue[T]) Equals(other T) bool {
	ret := _m.Called(other)

	if len(ret) == 0 {
		panic("no return value specified for Equals")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(T) bool); ok {
		r0 = rf(other)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewMockEqualsByValue creates a new instance of MockEqualsByValue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEqualsByValue[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEqualsByValue[T] {
	mock := &MockEqualsByValue[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
